### ISSUE TITLE
自动续写功能不能用

### ISSUE THREAD

**Issue by suzhouhu** [keep1234quiet/CoAuthor#2]
设置好各项，专等续写，结果我等了足足1个小时，不见它有任何动作！难道是我操作有误？翻译等均可实现

**Comment by keep1234quiet** [comment]
你好，我这边测试是正常的。

# 翻译功能可以实现说明：
1. API-KEY配置正确
2. 网络功能没有问题

# 要启用自动续写，请检查下面几项：
1. 配置中的“续写引导词”是否已正确填写，这一项可以自定义，默认内容为“按照我提供的内容继续写（不要回答多余的内容）”；
2. 自动续写开关是否已打开，请确保tab栏和配置界面的自动续写开关都处于开启状态（tab栏蓝色为开启，灰色为关闭；配置界面ON为开启），并点击保存配置；
3. 首次触发自动续写需要输入10个以上字符，后续再次触发需要输入6个以上字符（这里的字符其实是键盘上0-9,A-Z），尽量多输入一些字符，以便ChatGPT能够更好的了解你的意图；
4. 输入完成后，会在配置界面中保存的触发时间后向ChatGPT请求内容，右下角会有请求内容动画，不会一直转，有默认的超时时间（如果超过1min，可能这条结果不会返回了，原因可能有：网络问题，插件本身的问题，ChatGPT没有返回内容，APIKEY对应的账户欠费等），如果出现问题，可以尝试继续输入，如果仍然无法触发自动续写，可以尝试重启word；


![image](https://user-images.githubusercontent.com/48468402/236096546-b8ae9979-cccc-40ba-84d0-3defc2e565fe.png)

![image](https://user-images.githubusercontent.com/48468402/236096626-c19ff7fe-f26c-43f5-b120-0e012697e293.png)

![image](https://user-images.githubusercontent.com/48468402/236096420-384c17b6-7bba-4a5c-b5f9-b96af1da4d16.png)

**Comment by suzhouhu** [comment]
如何触发自动续写？需要手动点击那个按钮？还是需要在word中选中10个以上字符然后再点击自动续写？
我都折腾了两天了，麻烦加我QQ直接交流，肯定有问题的

**Comment by suzhouhu** [comment]
我的QQ: 767542048  微信：zuzhouh

**Comment by keep1234quiet** [comment]
> 

自动续写开关打开后，输入10个字符就会自动触发这个功能的，不需要其他的操作
